# Transcribed from NT Government, "Remote health services", https://nt.gov.au/wellbeing/remote-health/remote-health-services
# (page dated 31 Aug 2026, accessed 27 Sep 2026). Columns: region, location as listed, opening hours, operator.
NTH="NT Health"
ROWS = [
("Top End","Adelaide River","9am to 5pm; Emergencies 24/7",NTH),
("Top End","Batchelor","9am to 5pm; Emergencies 24/7",NTH),
("Top End","Belyuen","9am to 5pm; Emergencies 24/7",NTH),
("Top End","Gunbalanya (Oenpelli)","Mon-Wed 8:30am-12pm, 1-4pm; Thu 1-4pm; Fri 8:30am-12pm, 1-4pm","Red Lily Health Board Aboriginal Corporation"),
("Top End","Jabiru","9am to 5pm; Emergencies 24/7","Red Lily Health Board"),
("Top End","Maningrida","9am to 5pm; Emergencies 24/7","Mala'la Health Service Aboriginal Corporation"),
("Top End","Milikapiti","9am to 5pm; Emergencies",NTH),
("Top End","Minjilang","9am to 5pm; Emergencies 24/7","Red Lily Health Board"),
("Top End","Nauiyu Nambiyu (Daly River)","9am to 5pm; Emergencies 24/7",NTH),
("Top End","Palumpa","9am to 5pm; Emergencies 24/7",NTH),
("Top End","Peppimenarti","9am to 4:30pm; Emergencies 24/7",NTH),
("Top End","Pirlangimpi","9am to 5pm; Emergencies 24/7",NTH),
("Top End","Wadeye (Port Keats)","9am to 5pm; Emergencies 24/7",NTH),
("Top End","Warruwi","9am to 5pm; Emergencies 24/7","Red Lily Health Board"),
("Top End","Woodyculpaldiya","9am to 12pm; 1pm to 4pm",NTH),
("Top End","Wurrumiyanga (Nguiu)","9am to 5pm; Emergencies 24/7",NTH),
("East Arnhem","Alyangula","9am to 5pm; Emergencies 24/7",NTH),
("East Arnhem","Angurugu","9am to 5pm; Emergencies 24/7",NTH),
("East Arnhem","Milyakburra (Bickerton Island)","9am to 5pm; Emergencies 24/7",NTH),
("East Arnhem","Galiwin'ku (Elcho Island)","8am to 12pm; 1pm to 4:30pm","Miwatj Health Aboriginal Corporation"),
("East Arnhem","Galiwin'ku (Elcho Island) Homelands","","Marthakal Homelands Health Service"),
("East Arnhem","Gapuwiyak","9am to 5pm; Emergencies 24/7","Miwatj Health Aboriginal Corporation"),
("East Arnhem","Gunyangara","8:30am to 4:30pm","Miwatj Health Aboriginal Corporation"),
("East Arnhem","Laynhapuy Homelands","","Laynhapuy Aboriginal Community Controlled Health Services"),
("East Arnhem","Nhulunbuy Urban","8:30am to 4:30pm","Miwatj Health Aboriginal Corporation"),
("East Arnhem","Ramingining","Mon, Tue, Thu, Fri 8am-4:30pm; Wed 8am-12pm","Miwatj Health Aboriginal Corporation"),
("East Arnhem","Umbakumba","Mon-Thu 9am-4pm; Fri 9am-1pm",NTH),
("East Arnhem","Yirrkala","Mon-Thu 8am-4pm; Fri 8am-12pm","Miwatj Health Aboriginal Corporation"),
("East Arnhem","Yurrwi (Milingimbi)","Mon, Tue, Thu, Fri 8am-4:30pm; Wed 8am-12pm","Miwatj Health Aboriginal Corporation"),
("Big Rivers","Amanbidji (Kildurk)","Tuesday 10am to 2pm","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Barunga (Bamyili)","8am to 4:30pm","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Binjari","8:30am to 4pm","Wurli Wurlinjang Health Service"),
("Big Rivers","Borroloola","9am to 5pm; Emergencies 24/7",NTH),
("Big Rivers","Bulla","Mon, Wed, Fri 10am-2pm","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Daguragu (Wattie Creek)","","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Gulin (Bulman)","8am to 4:30pm","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Jilkminggan (Duck Creek)","8am to 4:30pm","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Kalkaringi (Wave Hill)","Mon-Thu 8:30am-4pm; Fri 1-4pm; Emergencies 24/7","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Lajamanu (Hooker Creek)","Mon-Thu 8:30am-4pm; Fri 1-4pm; Emergencies 24/7","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Lingara via Yarralin","Mon-Thu 8:30am-4pm; Fri 1-4pm; Emergencies 24/7","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Manyallaluk (Eva Valley)","9am to 5pm; Emergencies 24/7","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Mataranka","8am to 4:30pm","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Mialuni (Kildurk)","Tuesday 10am to 2pm","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Minyerri (Hodgeson Downs)","","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Ngukurr (Roper River)","8am to 4:30pm","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Numbulwar","Mon, Tue, Wed, Fri 9am-12pm; Thu 1-4pm",NTH),
("Big Rivers","Nitjpurru (Pigeon Hole)","Tue 10:30am-4pm; Wed 8:30am-4pm; Thu 8:30am-2pm","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Pine Creek","Tuesday 9am to 3pm",NTH),
("Big Rivers","Robinson River","8am to 5pm",NTH),
("Big Rivers","Timber Creek","Mon-Thu 8:30am-4pm; Fri 1-4pm; Emergencies 24/7","Katherine West Health Board Aboriginal Corporation"),
("Big Rivers","Urapunga (Rittarangu)","","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Wugularr (Beswick)","","Sunrise Health Service Aboriginal Corporation"),
("Big Rivers","Yarralin","Mon-Thu 8:30am-4pm; Fri 1-4pm; Emergencies 24/7","Katherine West Health Board Aboriginal Corporation"),
("Barkly","Aherrenge (Ampilawatja)","Mon, Tue, Wed, Fri 8:30am-12:30pm, 2:30-5:30pm; Thu 8:30am-12:30pm","Ampilatwatja Health Centre Aboriginal Corporation"),
("Barkly","Ali Curung","Mon-Wed 8am to 5pm",NTH),
("Barkly","Alpurrurulam (Lake Nash)","8am to 5pm; Emergencies 24/7",NTH),
("Barkly","Canteen Creek","8am to 5pm; Emergencies 24/7",NTH),
("Barkly","Elliot","8am to 5pm; Emergencies 24/7",NTH),
("Barkly","Epenarra (Wutunugurra)","Visiting service",NTH),
("Barkly","Tara (Neutral Junction)","8am to 5pm",NTH),
("Barkly","Tennant Creek Outstations","8am to 4:30pm","Anyinginyi Health Services Aboriginal Corporation"),
("Barkly","Tennant Creek Urban","Mon, Tue, Wed, Fri 8:30-11:30am, 1-4pm; Thu 8:30-11:30am","Anyinginyi Health Services Aboriginal Corporation"),
("Barkly","Urapuntja (Utopia)","8am to 5pm; Emergencies 24/7","Urapuntja Health Service"),
("Central Australia","Amoonguna","Mon, Tue, Wed, Fri 8am-4:30pm; Thu 8am-12:30pm","Central Australian Aboriginal Congress / Amoonguna Health Service Board"),
("Central Australia","Aputula (Finke)","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Harts Range (Atitjere)","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Bonya","Visiting service; Emergencies 24/7",NTH),
("Central Australia","Engawala (Alcoota)","Visiting service; Emergencies 24/7",NTH),
("Central Australia","Haasts Bluff (Ikuntji)","Visiting service; Emergencies 24/7",NTH),
("Central Australia","Imanpa (Mt Ebenezer)","Tue 10:30am-5pm; Wed 8:30am-2pm","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
("Central Australia","Kaltukatjara (Docker River)","Mon, Tue 8:30am-5pm; Wed 9:30am-5pm; Thu 8:30am-12pm; Fri 8:30am-5pm","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
("Central Australia","Kintore","9am to 12pm; 2pm to 5pm","Pintupi Homelands Health Service"),
("Central Australia","Ltyentye Apurte (Santa Teresa)","Mon, Tue, Wed, Fri 8:30am-12pm, 1-5pm; Thu 8:30am-12pm, 3:30-4:30pm","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
("Central Australia","Laramba (Napperby)","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Mt Liebig (Amunturrngu)","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Mutitjulu","Mon, Tue, Wed, Fri 8:30am-4pm; Thu 8:30am-12pm","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
("Central Australia","Hermannsburg (Ntaria)","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Ntaria (Hermannsburg) PHC","","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
("Central Australia","Nturiya (Ti-Tree Station)","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Nyirippi (Waite Creek)","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Pmara Jutunta (6 Mile)","Visiting service; Emergencies 24/7",NTH),
("Central Australia","Titjikala (Maryvale)","8:30am to 4:30pm; Emergencies 24/7",NTH),
("Central Australia","Utju (Areonga)","Mon, Tue, Wed, Fri 8:30am-5pm; Thu 8:30am-12pm","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
("Central Australia","Wallace Rockhole","Wednesday 9am to 5pm","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
("Central Australia","Watarrka (Kings Canyon)","Mon-Thu 9am-4:30pm; Fri 9am-12pm",NTH),
("Central Australia","Willowra","9am to 5pm",NTH),
("Central Australia","Yuendumu","8am to 5pm; Emergencies 24/7",NTH),
("Central Australia","Yulara (Uluru)","Mon, Tue 8:30am-5pm; Wed 9:30am-5pm; Thu 8:30am-12pm; Fri 8:30am-5pm","Central Australian Aboriginal Congress / Mpwelarre Health Aboriginal Corporation"),
]
